[package]
name = "openvpn-auth-user-pass"
version = "1.0.0"
authors = ["bossma <bossma@yeah.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4"